import asyncio
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy import select
from app.core.config import settings
from app.models.industry_benchmark import IndustryBenchmark

engine = create_async_engine(settings.ASYNC_DATABASE_URL, echo=False)
AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False)

INITIAL_BENCHMARKS = [
    # ========== FUENTE 1: UPTIME INSTITUTE 2021 ==========
    IndustryBenchmark(
        benchmark_id="uptime-2021-visibilidad",
        dimension="visibilidad",
        source_name="Uptime Institute 2021",
        source_year=2021,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="Herramientas aisladas por equipo, monitoreo básico PUE exclusivo",
        level_1_metric_value=40.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Dashboard parcial (2 de 3 capas), rastreo PUE + agua + renovables",
        level_3_metric_value=50.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Dashboard unificado tiempo real (3 capas) + Scope 1-2-3 integral",
        level_5_metric_value=85.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="uptime-2021-friccion",
        dimension="friccion",
        source_name="Uptime Institute 2021",
        source_year=2021,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="69% sufrió outages en 3 años (43% energía, 14% cooling, 79% humano)",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Outages ocasionales pero bajo control",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Cero outages en 3 años, prevención activa",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="uptime-2021-latencia",
        dimension="latencia",
        source_name="Uptime Institute 2021",
        source_year=2021,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="No menciona latencia operativa específica",
        level_1_metric_value=86400.0,
        level_1_metric_unit="seconds",
        level_1_likert_equivalent=1,
        level_3_description="Coordinación semi-manual en minutos",
        level_3_metric_value=3600.0,
        level_3_metric_unit="seconds",
        level_3_likert_equivalent=3,
        level_5_description="Coordinación con automation, minutos",
        level_5_metric_value=1800.0,
        level_5_metric_unit="seconds",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="uptime-2021-auto_cuantificacion",
        dimension="auto_cuantificacion",
        source_name="Uptime Institute 2021",
        source_year=2021,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="60% no sabe capacidad perdida, a ciegas",
        level_1_metric_value=40.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="50% cuantifica parcialmente con datos",
        level_3_metric_value=50.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="100% cuantifica exactamente en tiempo real",
        level_5_metric_value=85.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="uptime-2021-bloqueantes",
        dimension="bloqueantes",
        source_name="Uptime Institute 2021",
        source_year=2021,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="47% staffing insuficiente, 75% supply chain retrasos",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Limitaciones ocasionales",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Sin bloqueantes críticos, procesos ágiles",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),

    # ========== FUENTE 2: DECUSATIS SDN 2015 ==========
    IndustryBenchmark(
        benchmark_id="decusatis-2015-visibilidad",
        dimension="visibilidad",
        source_name="DeCusatis SDN 2015",
        source_year=2015,
        source_region="USA",
        source_reliability=0.85,
        level_1_description="Monitoreo parcial, sin visibilidad cross-layer",
        level_1_metric_value=30.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Monitoreo SNMP/Ganglia en tiempo real",
        level_3_metric_value=60.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Visibilidad completa con SDN, reconfiguración automática",
        level_5_metric_value=90.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="decusatis-2015-friccion",
        dimension="friccion",
        source_name="DeCusatis SDN 2015",
        source_year=2015,
        source_region="USA",
        source_reliability=0.85,
        level_1_description="Arquitecturas estáticas fallan ante picos 6x la media",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Manejo moderado de picos 3x",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Escalado automático, picos controlados",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="decusatis-2015-latencia",
        dimension="latencia",
        source_name="DeCusatis SDN 2015",
        source_year=2015,
        source_region="USA",
        source_reliability=0.85,
        level_1_description="Manual: semanas o meses entre DCs",
        level_1_metric_value=2592000.0,
        level_1_metric_unit="seconds",
        level_1_likert_equivalent=1,
        level_3_description="Semi-automático con hardware rígido",
        level_3_metric_value=1800.0,
        level_3_metric_unit="seconds",
        level_3_likert_equivalent=3,
        level_5_description="Software-defined: <60 segundos",
        level_5_metric_value=60.0,
        level_5_metric_unit="seconds",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="decusatis-2015-auto_cuantificacion",
        dimension="auto_cuantificacion",
        source_name="DeCusatis SDN 2015",
        source_year=2015,
        source_region="USA",
        source_reliability=0.85,
        level_1_description="Desconocimiento de capacidad perdida",
        level_1_metric_value=30.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Cuantificación parcial con umbrales",
        level_3_metric_value=75.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Umbrales claros para saturación de servidores",
        level_5_metric_value=95.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="decusatis-2015-bloqueantes",
        dimension="bloqueantes",
        source_name="DeCusatis SDN 2015",
        source_year=2015,
        source_region="USA",
        source_reliability=0.85,
        level_1_description="Reconfiguración manual, rigidez de hardware WDM",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Intervención humana ocasional requerida",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Automatización completa sin intervención",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),

    # ========== FUENTE 3: JMI POLICY BRIEF 2025 ==========
    IndustryBenchmark(
        benchmark_id="jmi-2025-visibilidad",
        dimension="visibilidad",
        source_name="JMI Policy Brief 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Solo monitoreo de PUE, sin agua ni renovables",
        level_1_metric_value=43.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Compilación de métricas de agua (Uptime Survey 2024)",
        level_3_metric_value=43.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Integración completa de agua + energía + renovables",
        level_5_metric_value=85.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="jmi-2025-friccion",
        dimension="friccion",
        source_name="JMI Policy Brief 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Retrasos en la red eléctrica, queue shopping",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Desconexiones ocasionales de grid",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Interconexión estable y optimizada",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="jmi-2025-latencia",
        dimension="latencia",
        source_name="JMI Policy Brief 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Construcción física: 18-24 meses",
        level_1_metric_value=1555200.0,
        level_1_metric_unit="seconds",
        level_1_likert_equivalent=1,
        level_3_description="Provisioning de capacidad: 2-7 días",
        level_3_metric_value=604800.0,
        level_3_metric_unit="seconds",
        level_3_likert_equivalent=3,
        level_5_description="Provisioning rápido: <4 horas",
        level_5_metric_value=14400.0,
        level_5_metric_unit="seconds",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="jmi-2025-auto_cuantificacion",
        dimension="auto_cuantificacion",
        source_name="JMI Policy Brief 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="57% no mide impacto ambiental hídrico",
        level_1_metric_value=43.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Medición parcial de impacto ambiental",
        level_3_metric_value=43.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Cuantificación exacta: water + carbon + energy",
        level_5_metric_value=85.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="jmi-2025-bloqueantes",
        dimension="bloqueantes",
        source_name="JMI Policy Brief 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Speed to Power: reguladores lentos, aprobaciones largas",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Descalce ocasional con reguladores",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Coordinación fluida con autoridades",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),

    # ========== FUENTE 4: NARTEY 2025 ==========
    IndustryBenchmark(
        benchmark_id="nartey-2025-visibilidad",
        dimension="visibilidad",
        source_name="Nartey 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="Solo PUE, sin Scope 1-2-3 ni impacto hídrico",
        level_1_metric_value=40.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="PUE + consideraciones ambientales básicas",
        level_3_metric_value=50.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Scope 1-2-3 completo, huella hídrica integral",
        level_5_metric_value=85.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="nartey-2025-friccion",
        dimension="friccion",
        source_name="Nartey 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="40% del consumo va a cooling, ineficiencia alta",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Cooling overhead en rango normal 20-30%",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Cooling optimizado <15% overhead",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="nartey-2025-latencia",
        dimension="latencia",
        source_name="Nartey 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="Descalce de adaptación: IA crece más rápido que cooling",
        level_1_metric_value=86400.0,
        level_1_metric_unit="seconds",
        level_1_likert_equivalent=1,
        level_3_description="Adaptación moderada a cambios de carga",
        level_3_metric_value=3600.0,
        level_3_metric_unit="seconds",
        level_3_likert_equivalent=3,
        level_5_description="Adaptación ágil, sin descalce",
        level_5_metric_value=1800.0,
        level_5_metric_unit="seconds",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="nartey-2025-auto_cuantificacion",
        dimension="auto_cuantificacion",
        source_name="Nartey 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="Consumo base desconocido (500-1200W por servidor)",
        level_1_metric_value=40.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Consumo conocido, overhead 40% de cooling",
        level_3_metric_value=60.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Overhead total cuantificado: 1.9 Gt CO2/año (2025)",
        level_5_metric_value=85.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="nartey-2025-bloqueantes",
        dimension="bloqueantes",
        source_name="Nartey 2025",
        source_year=2025,
        source_region="Global",
        source_reliability=0.90,
        level_1_description="Matriz energética fósil local (ej. Polonia vs Noruega)",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Mix energético moderado con renovables",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Matriz energética verde, bajo carbono",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),

    # ========== FUENTE 5: VIRTUALIZATION 2018 ==========
    IndustryBenchmark(
        benchmark_id="virt-2018-visibilidad",
        dimension="visibilidad",
        source_name="Virtualization 2018",
        source_year=2018,
        source_region="Global",
        source_reliability=0.85,
        level_1_description="Monitoreo limitado de capa virtualización",
        level_1_metric_value=50.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Medición de CPU, memoria, ancho de banda",
        level_3_metric_value=70.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Telemetría fina de CPU, memoria, red, I/O",
        level_5_metric_value=75.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="virt-2018-friccion",
        dimension="friccion",
        source_name="Virtualization 2018",
        source_year=2018,
        source_region="Global",
        source_reliability=0.85,
        level_1_description="Pérdida de capacidad 5-15% por Hypervisor overhead",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Overhead balanceado 5-8%",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Overhead mínimo <2% (Contenedores)",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="virt-2018-latencia",
        dimension="latencia",
        source_name="Virtualization 2018",
        source_year=2018,
        source_region="Global",
        source_reliability=0.85,
        level_1_description="VMs: 10-45 segundos start-up time",
        level_1_metric_value=30.0,
        level_1_metric_unit="seconds",
        level_1_likert_equivalent=1,
        level_3_description="VMs moderadas: 10 segundos",
        level_3_metric_value=10.0,
        level_3_metric_unit="seconds",
        level_3_likert_equivalent=3,
        level_5_description="Contenedores: <1 segundo start-up",
        level_5_metric_value=1.0,
        level_5_metric_unit="seconds",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="virt-2018-auto_cuantificacion",
        dimension="auto_cuantificacion",
        source_name="Virtualization 2018",
        source_year=2018,
        source_region="Global",
        source_reliability=0.85,
        level_1_description="Overhead desconocido, uso subóptimo",
        level_1_metric_value=50.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Overhead medido (5-15% VMs vs <2% Contenedores)",
        level_3_metric_value=70.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Overhead exacto, optimización al máximo",
        level_5_metric_value=85.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="virt-2018-bloqueantes",
        dimension="bloqueantes",
        source_name="Virtualization 2018",
        source_year=2018,
        source_region="Global",
        source_reliability=0.85,
        level_1_description="Trade-off aislamiento vs desempeño, normas de seguridad rígidas",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Balance aceptable entre seguridad y performance",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Seguridad sin sacrificar agilidad de contenedores",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),

    # ========== FUENTE 6: DECOFFEE 2026 ==========
    IndustryBenchmark(
        benchmark_id="decoffee-2026-visibilidad",
        dimension="visibilidad",
        source_name="DECOFFEE 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Telemetry parcial, monitoreo por componente",
        level_1_metric_value=70.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Telemetry con W-window=10, matrices de carga histórica",
        level_3_metric_value=85.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Telemetry completo + ML forecasting, 20 Edge + Cloud Agents",
        level_5_metric_value=95.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="decoffee-2026-friccion",
        dimension="friccion",
        source_name="DECOFFEE 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Drop rate 19%, saturación de colas público/privadas",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Drop rate 15% con LSTM forecasting",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Drop rate <1%, anti-thrashing penalty",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="decoffee-2026-latencia",
        dimension="latencia",
        source_name="DECOFFEE 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Offloading manual, timeout >10 segundos",
        level_1_metric_value=10.0,
        level_1_metric_unit="seconds",
        level_1_likert_equivalent=1,
        level_3_description="Offloading semi-automático, horizontal + vertical",
        level_3_metric_value=2.0,
        level_3_metric_unit="seconds",
        level_3_likert_equivalent=3,
        level_5_description="Offloading 100% automático DRL/MAPPO, <0.1 segundos",
        level_5_metric_value=0.1,
        level_5_metric_unit="seconds",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="decoffee-2026-auto_cuantificacion",
        dimension="auto_cuantificacion",
        source_name="DECOFFEE 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Drop rate 19%, sin forecasting LSTM",
        level_1_metric_value=40.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Drop rate 15% con LSTM, reducción 4%",
        level_3_metric_value=70.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Drop rate <1%, forecasting óptimo, 45-60% ahorro energía",
        level_5_metric_value=90.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="decoffee-2026-bloqueantes",
        dimension="bloqueantes",
        source_name="DECOFFEE 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Heterogeneidad de red (30 Mbps horizontal vs 10 Mbps vertical)",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Red heterogénea pero manejable",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="Red homogénea y optimizada",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),

    # ========== FUENTE 7: FA-MAPPO 2026 ==========
    IndustryBenchmark(
        benchmark_id="famappo-2026-visibilidad",
        dimension="visibilidad",
        source_name="FA-MAPPO 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Monitoreo parcial sin LSTM window",
        level_1_metric_value=60.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Encoder LSTM con ventanas deslizantes (k=20)",
        level_3_metric_value=85.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="LSTM + integración continua en loop de optimización",
        level_5_metric_value=90.0,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="famappo-2026-friccion",
        dimension="friccion",
        source_name="FA-MAPPO 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="SLA violations 1.18% (sin Forecast-Assisted)",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="SLA violations 0.84% (mejora moderada)",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="SLA violations 0.67% (43.2% reducción relativa vs Trans-PPO)",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="famappo-2026-latencia",
        dimension="latencia",
        source_name="FA-MAPPO 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Inferencia lenta sin ML optimizado",
        level_1_metric_value=5.0,
        level_1_metric_unit="milliseconds",
        level_1_likert_equivalent=1,
        level_3_description="Inferencia moderada con ML",
        level_3_metric_value=3.0,
        level_3_metric_unit="milliseconds",
        level_3_likert_equivalent=3,
        level_5_description="Inferencia ultra-rápida FA-MAPPO: 1.4 ms",
        level_5_metric_value=1.4,
        level_5_metric_unit="milliseconds",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="famappo-2026-auto_cuantificacion",
        dimension="auto_cuantificacion",
        source_name="FA-MAPPO 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Utilización <40% (muy baja, stranded capacity)",
        level_1_metric_value=40.0,
        level_1_metric_unit="%",
        level_1_likert_equivalent=1,
        level_3_description="Utilización 50-60% (moderada)",
        level_3_metric_value=60.0,
        level_3_metric_unit="%",
        level_3_likert_equivalent=3,
        level_5_description="Utilización 72.02% (real Google Traces, SOTA)",
        level_5_metric_value=72.02,
        level_5_metric_unit="%",
        level_5_likert_equivalent=5,
    ),
    IndustryBenchmark(
        benchmark_id="famappo-2026-bloqueantes",
        dimension="bloqueantes",
        source_name="FA-MAPPO 2026",
        source_year=2026,
        source_region="Global",
        source_reliability=0.95,
        level_1_description="Response lag en auto-scalers HPA reactivos",
        level_1_metric_value=1.0,
        level_1_metric_unit="nivel",
        level_1_likert_equivalent=1,
        level_3_description="Auto-scalers con latencia moderada",
        level_3_metric_value=3.0,
        level_3_metric_unit="nivel",
        level_3_likert_equivalent=3,
        level_5_description="FA-MAPPO: Thrashing penalty, respuesta óptima",
        level_5_metric_value=5.0,
        level_5_metric_unit="nivel",
        level_5_likert_equivalent=5,
    ),
]


async def seed_data():
    print("🌱 Iniciando la carga de datos inicial (Seed)...")

    async with AsyncSessionLocal() as session:
        # Verificamos si ya hay datos para no duplicar
        result = await session.execute(select(IndustryBenchmark))
        existing_benchmarks = result.scalars().all()

        if existing_benchmarks:
            print(f"⚠️ La tabla 'industry_benchmarks' ya tiene {len(existing_benchmarks)} datos. Omitiendo el seed.")
            return

        # Si está vacía, insertamos la data
        session.add_all(INITIAL_BENCHMARKS)
        await session.commit()

        print(f"✅ ¡Éxito! Se insertaron {len(INITIAL_BENCHMARKS)} benchmarks en la base de datos.")


if __name__ == "__main__":
    asyncio.run(seed_data())