"""init_tables

Revision ID: 35131bf6e880
Revises: 
Create Date: 2026-08-05 21:03:06.412456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35131bf6e880'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_benchmarks',
    sa.Column('benchmark_id', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('source_region', sa.String(length=50), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('level_1_description', sa.Text(), nullable=False),
    sa.Column('level_1_metric_value', sa.Float(), nullable=True),
    sa.Column('level_1_metric_unit', sa.String(length=20), nullable=True),
    sa.Column('level_1_likert_equivalent', sa.Integer(), nullable=False),
    sa.Column('level_3_description', sa.Text(), nullable=False),
    sa.Column('level_3_metric_value', sa.Float(), nullable=True),
    sa.Column('level_3_metric_unit', sa.String(length=20), nullable=True),
    sa.Column('level_3_likert_equivalent', sa.Integer(), nullable=False),
    sa.Column('level_5_description', sa.Text(), nullable=False),
    sa.Column('level_5_metric_value', sa.Float(), nullable=True),
    sa.Column('level_5_metric_unit', sa.String(length=20), nullable=True),
    sa.Column('level_5_likert_equivalent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('benchmark_id')
    )
    op.create_index(op.f('ix_industry_benchmarks_dimension'), 'industry_benchmarks', ['dimension'], unique=False)
    op.create_index(op.f('ix_industry_benchmarks_source_region'), 'industry_benchmarks', ['source_region'], unique=False)
    op.create_index(op.f('ix_industry_benchmarks_source_year'), 'industry_benchmarks', ['source_year'], unique=False)
    op.create_table('user_evaluations',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('facility_size', sa.String(length=20), nullable=False),
    sa.Column('facility_type', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('p1_visibilidad_herramientas', sa.Integer(), nullable=False),
    sa.Column('p2_visibilidad_dashboards', sa.Integer(), nullable=False),
    sa.Column('p3_visibilidad_telemetry', sa.Integer(), nullable=False),
    sa.Column('p4_friccion_energia', sa.Integer(), nullable=False),
    sa.Column('p5_friccion_cooling', sa.Integer(), nullable=False),
    sa.Column('p6_latencia_manual', sa.Integer(), nullable=False),
    sa.Column('p7_latencia_semi_auto', sa.Integer(), nullable=False),
    sa.Column('p8_latencia_full_auto', sa.Integer(), nullable=False),
    sa.Column('p9_auto_cuant_pue', sa.Integer(), nullable=False),
    sa.Column('p10_auto_cuant_utilizacion', sa.Integer(), nullable=False),
    sa.Column('p11_bloqueantes_staffing', sa.Integer(), nullable=False),
    sa.Column('p12_bloqueantes_supply', sa.Integer(), nullable=False),
    sa.Column('p13_bloqueantes_energy', sa.Integer(), nullable=False),
    sa.Column('p14_bloqueantes_regulacion', sa.Integer(), nullable=False),
    sa.Column('p15_bloqueantes_expertise', sa.Integer(), nullable=False),
    sa.Column('score_visibilidad', sa.Float(), nullable=True),
    sa.Column('score_friccion', sa.Float(), nullable=True),
    sa.Column('score_latencia', sa.Float(), nullable=True),
    sa.Column('score_auto_cuantificacion', sa.Float(), nullable=True),
    sa.Column('score_bloqueantes', sa.Float(), nullable=True),
    sa.Column('percentile_visibilidad', sa.Integer(), nullable=True),
    sa.Column('percentile_friccion', sa.Integer(), nullable=True),
    sa.Column('percentile_latencia', sa.Integer(), nullable=True),
    sa.Column('percentile_auto_cuantificacion', sa.Integer(), nullable=True),
    sa.Column('percentile_bloqueantes', sa.Integer(), nullable=True),
    sa.Column('percentile_general', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_evaluations')
    op.drop_index(op.f('ix_industry_benchmarks_source_year'), table_name='industry_benchmarks')
    op.drop_index(op.f('ix_industry_benchmarks_source_region'), table_name='industry_benchmarks')
    op.drop_index(op.f('ix_industry_benchmarks_dimension'), table_name='industry_benchmarks')
    op.drop_table('industry_benchmarks')
    # ### end Alembic commands ###
