"""add_composite_index_facility_size_region

Revision ID: 80b26b8058b5
Revises: 35131bf6e880
Create Date: 2026-08-15 23:14:32.506623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b26b8058b5'
down_revision: Union[str, Sequence[str], None] = '35131bf6e880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_evaluations_facility_size'), 'user_evaluations', ['facility_size'], unique=False)
    op.create_index(op.f('ix_user_evaluations_region'), 'user_evaluations', ['region'], unique=False)
    op.create_index('ix_user_evaluations_size_region', 'user_evaluations', ['facility_size', 'region'], unique=False)
    op.create_check_constraint('ck_p10_range', 'user_evaluations', 'p10_auto_cuant_utilizacion BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p11_range', 'user_evaluations', 'p11_bloqueantes_staffing BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p12_range', 'user_evaluations', 'p12_bloqueantes_supply BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p13_range', 'user_evaluations', 'p13_bloqueantes_energy BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p14_range', 'user_evaluations', 'p14_bloqueantes_regulacion BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p15_range', 'user_evaluations', 'p15_bloqueantes_expertise BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p1_range', 'user_evaluations', 'p1_visibilidad_herramientas BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p2_range', 'user_evaluations', 'p2_visibilidad_dashboards BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p3_range', 'user_evaluations', 'p3_visibilidad_telemetry BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p4_range', 'user_evaluations', 'p4_friccion_energia BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p5_range', 'user_evaluations', 'p5_friccion_cooling BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p6_range', 'user_evaluations', 'p6_latencia_manual BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p7_range', 'user_evaluations', 'p7_latencia_semi_auto BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p8_range', 'user_evaluations', 'p8_latencia_full_auto BETWEEN 1 AND 5')
    op.create_check_constraint('ck_p9_range', 'user_evaluations', 'p9_auto_cuant_pue BETWEEN 1 AND 5')
    op.create_check_constraint('ck_user_evaluations_facility_size', 'user_evaluations', "facility_size IN ('small', 'medium', 'large', 'mega')")
    op.create_check_constraint('ck_user_evaluations_region', 'user_evaluations', "region IN ('latam', 'usa', 'europe', 'apac')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_user_evaluations_region', 'user_evaluations', type_='check')
    op.drop_constraint('ck_user_evaluations_facility_size', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p9_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p8_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p7_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p6_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p5_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p4_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p3_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p2_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p1_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p15_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p14_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p13_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p12_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p11_range', 'user_evaluations', type_='check')
    op.drop_constraint('ck_p10_range', 'user_evaluations', type_='check')
    op.drop_index('ix_user_evaluations_size_region', table_name='user_evaluations')
    op.drop_index(op.f('ix_user_evaluations_region'), table_name='user_evaluations')
    op.drop_index(op.f('ix_user_evaluations_facility_size'), table_name='user_evaluations')
    # ### end Alembic commands ###
